osx_instance:
    image: mojave-xcode-10.2-flutter

build_example_android_task:
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd example
    - flutter build apk

build_example_ios_task:
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd example
    - cd ios
    - pod install --repo-update
    - cd ..
    - flutter build ios --no-codesign