task:
  name: Build Android example
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd example
    - flutter build appbundle

task:
  name: Build iOS example
  osx_instance:
    image: mojave-flutter
  pub_cache:
    folder: ~/.pub-cache
  update_pods_script: pod repo update # to fetch all the latest versions
  build_script:
    - cd example
    - flutter build ios --no-codesign
